reg/reg/Models/parveenmodel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Parthi\Documents\GitHub\Myrepos\reg\reg\Models\parveenmodel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

reg/reg/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using reg.Models;
using Rotativa;
using Rotativa.MVC;
using QRCoder;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;

namespace reg.Controllers
{
    public class HomeController : Controller
    {
        parveenEntities entities = new parveenEntities();
        public ActionResult Index()
        {
            //return View();
           
            var data = entities.tbl_Reg.Select(x => x);
            return View(data.ToList());
        }
        public ActionResult PrintAllReport()
        {
            var report = new ActionAsPdf("Index");
            return report;
        }
        public ActionResult IDcard(int id)
        {
            var cus = entities.tbl_Reg.Where(u => u.Cus_Id==id).First();
            ViewBag.Name = cus.Cus_Name;
            ViewBag.Service = cus.Cus_Services;
            using (MemoryStream ms = new MemoryStream())
            {

                string level = "Q";
                QRCodeGenerator qrGenerator = new QRCodeGenerator();
                QRCodeGenerator.ECCLevel eccLevel = (QRCodeGenerator.ECCLevel)(level == "L" ? 0 : level == "M" ? 1 : level == "Q" ? 2 : 3);
                using (QRCodeData qrCodeData = qrGenerator.CreateQrCode(cus.Cus_Mobile, eccLevel))
                {
                    using (QRCode qrCode = new QRCode(qrCodeData))
                    {

                        using (Bitmap bitMap = qrCode.GetGraphic(20))
                        {
                            bitMap.Save(ms, ImageFormat.Png);
                            ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                          
                        }
                    }
                }
                // QRCodeGenerator.QRCode qrCode = new QRCode(qrCodeData)

            }


            return View(cus);
        }
        public ActionResult PrintQRcode(int id)
        {
            var report = new ActionAsPdf("IDcard", new { id = id });
            return report;
        }
        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return View();
        //}

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}
    }
}

reg/reg/Controllers/RegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using reg.Models;
using System.IO;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Mail;
using System.Text;
using System.Net;

namespace reg.Controllers
{
    public class RegController : Controller
    {
        // GET: Reg
        public ActionResult Index()
        {
           


            return View();
        }
        [ValidateInput(true)]
        [HttpPost]
        public ActionResult Register(tbl_Reg regdata)
        {
            if (ModelState.IsValid)
            {
                //var Mobileno = Convert.ToString(Request["txtAmount"].ToString());
                using (var context = new regmodelcontext())
                {
                    var user = context.regusers.Where(u => u.Cus_Mobile == regdata.Cus_Mobile).FirstOrDefault();

                    if (user == null)
                    {
                        context.regusers.Add(regdata);
                        context.SaveChanges();
                       // return View("Success");
                        return RedirectToAction("Success", new { Qrimput = regdata.Cus_Mobile});
                    }
                    else
                    {
                        return View("Failure");
                    }
                }
            }
            return View("Success");
        }
        public ActionResult Success(string Qrimput)
        {
            using (MemoryStream ms = new MemoryStream())
            {

                string level = "Q";
                QRCodeGenerator qrGenerator = new QRCodeGenerator();
                QRCodeGenerator.ECCLevel eccLevel = (QRCodeGenerator.ECCLevel)(level == "L" ? 0 : level == "M" ? 1 : level == "Q" ? 2 : 3);
                using (QRCodeData qrCodeData = qrGenerator.CreateQrCode(Qrimput, eccLevel))
                {
                    using (QRCode qrCode = new QRCode(qrCodeData))
                    {

                        using (Bitmap bitMap = qrCode.GetGraphic(20))
                        {
                            bitMap.Save(ms, ImageFormat.Png);
                            ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                            mailsend(ViewBag.QRCodeImage);
                        }
                    }
                }
               // QRCodeGenerator.QRCode qrCode = new QRCode(qrCodeData)
               
            }
            return View();
        }

        public ActionResult Failure()
        {
            return View();
        }

        protected void mailsend(string img)
        {
            try
            {
                SmtpClient client = new SmtpClient();
                client.Port = 587;
                client.Host = "smtp.gmail.com";
                client.EnableSsl = true;
                client.Timeout = 10000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new System.Net.NetworkCredential("slogicsolutions@gmail.com", "Admin123$");
                String msg = "<html><body>this is a <img src=\"" + img + "\"></body></html>";
                MailMessage mm = new MailMessage("slogicsolutions@gmail.com", "praj587@gmail.com", "test", "test");
                mm.BodyEncoding = UTF8Encoding.UTF8;
                mm.DeliveryNotificationOptions = DeliveryNotificationOptions.OnFailure;

                client.Send(mm);


            }

            catch (Exception ex)
            { Response.Write("Failed"); }
        }
    }
}

reg/reg/Views/Home/IDcard.cshtml
@model reg.Models.tbl_Reg

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IDcard</title>
    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 300px;
            margin: auto;
            text-align: center;
            font-family: arial;
        }

        .title {
            color: grey;
            font-size: 18px;
        }

        button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

        a {
            text-decoration: none;
            font-size: 22px;
            color: black;
        }

            button:hover, a:hover {
                opacity: 0.7;
            }
    </style>
</head>
<body>
    <h2 style="text-align:center">PARVEEN TRAVELS ID</h2>

    <div class="card">
        @if (ViewBag.QRCodeImage != null)
        {
            <img id="imgQR" src="@ViewBag.QRCodeImage" alt="" style="height:150px;width:150px" />
        }


        <h1>@ViewBag.Name</h1>
        <p class="title">@ViewBag.Service</p>
       
        
        <p><button>Contact</button></p>
</body>
</html>

reg/reg/Views/Home/Index.cshtml
@model IEnumerable<reg.Models.tbl_Reg>
@using GridMvc.Html

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
   
     
 

    <h2>Customers</h2>

    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

    <div class="code-cut">
        @Html.Grid(Model).Columns(columns =>
   {
       // columns.Add().Encoded(false).Sanitized(false).SetWidth(10).RenderValueAs(o => Html.CheckBox("checked", false));
       columns.Add(c => c.Cus_Id).Titled("Registration ID").Filterable(false);
       columns.Add(c => c.Cus_Name).Titled("Customer Name").Filterable(true);
       columns.Add(c => c.Cus_Mobile).Titled("Mobile").Filterable(true);
       columns.Add(c => c.Cus_Services).Titled("Service").Filterable(true);
       columns.Add()
       .Encoded(false)
       .Sanitized(false)
       .SetWidth(30)
       .Filterable(false)
       .RenderValueAs(o => Html.ActionLink("PrintQR", "PrintQRcode", new { id = o.Cus_Id }));

   }).WithPaging(10).Sortable(true)
    </div>
    
</body>
</html>

reg/reg/Views/Reg/Index.cshtml
@model reg.Models.tbl_Reg

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_reglayout.cshtml";
}



@using (Html.BeginForm("Register", "Reg", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    <div class="form-group">
       @* <img id="imgQR" src="https://img3.hkrtcdn.com/842/prd_84162_c_m.jpg" style="height:125px;width:125px;float:right" class="rounded float-left" alt="https://img3.hkrtcdn.com/842/prd_84162_c_m.jpg">*@
       
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cus_Name)

            @Html.EditorFor(model => model.Cus_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cus_Name, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cus_Mobile)

            @Html.EditorFor(model => model.Cus_Mobile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cus_Mobile, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cus_Company)

            @Html.EditorFor(model => model.Cus_Company, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cus_Company, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cus_Services)

            @Html.EditorFor(model => model.Cus_Services, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cus_Services, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>

        }





        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

reg/reg/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

reg/reg/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>